[package]
name = "rvecsim"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ndarray = "0.16"
num-complex = "0.4"
rand = "0.8"
rayon = "1"
pyo3 = { version = "0.24", features = ["num-complex"], optional = true }

[features]
pyo3 = ["dep:pyo3"]
